-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 13:04:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `id` INT NOT NULL,
  `dateOfCreation` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Accounts_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Accounts_id`),
  INDEX `fk_Users_Accounts_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Accounts`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `mydb`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `idReservations` INT NOT NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`idReservations`, `Accounts_id`),
  INDEX `fk_Reservations_Accounts1_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `mydb`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemRecommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemRecommendations` (
  `idItemRecommendations` INT NOT NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`idItemRecommendations`, `Accounts_id`),
  INDEX `fk_ItemRecommendations_Accounts1_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_ItemRecommendations_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `mydb`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `isbn` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `publishingYear` YEAR(4) NOT NULL,
  `author` VARCHAR(45) NULL,
  `ItemRecommendations_idItemRecommendations1` INT NOT NULL,
  `ItemRecommendations_Accounts_id1` INT NOT NULL,
  PRIMARY KEY (`isbn`, `ItemRecommendations_idItemRecommendations1`, `ItemRecommendations_Accounts_id1`),
  INDEX `fk_Books_ItemRecommendations1_idx` (`ItemRecommendations_idItemRecommendations1` ASC, `ItemRecommendations_Accounts_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Books_ItemRecommendations1`
    FOREIGN KEY (`ItemRecommendations_idItemRecommendations1` , `ItemRecommendations_Accounts_id1`)
    REFERENCES `mydb`.`ItemRecommendations` (`idItemRecommendations` , `Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `idLoans` INT NOT NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`idLoans`, `Accounts_id`),
  INDEX `fk_Loans_Accounts1_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `mydb`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DVDs` (
  `title` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `genre` VARCHAR(45) NULL,
  `ItemRecommendations_idItemRecommendations1` INT NOT NULL,
  `ItemRecommendations_Accounts_id1` INT NOT NULL,
  PRIMARY KEY (`title`, `releaseDate`, `ItemRecommendations_idItemRecommendations1`, `ItemRecommendations_Accounts_id1`),
  INDEX `fk_DVDs_ItemRecommendations1_idx` (`ItemRecommendations_idItemRecommendations1` ASC, `ItemRecommendations_Accounts_id1` ASC) VISIBLE,
  CONSTRAINT `fk_DVDs_ItemRecommendations1`
    FOREIGN KEY (`ItemRecommendations_idItemRecommendations1` , `ItemRecommendations_Accounts_id1`)
    REFERENCES `mydb`.`ItemRecommendations` (`idItemRecommendations` , `Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CDs` (
  `title` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NULL,
  `recordLabel` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `ItemRecommendations_idItemRecommendations` INT NOT NULL,
  `ItemRecommendations_Accounts_id` INT NOT NULL,
  PRIMARY KEY (`title`, `artist`, `ItemRecommendations_idItemRecommendations`, `ItemRecommendations_Accounts_id`),
  INDEX `fk_CDs_ItemRecommendations1_idx` (`ItemRecommendations_idItemRecommendations` ASC, `ItemRecommendations_Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_CDs_ItemRecommendations1`
    FOREIGN KEY (`ItemRecommendations_idItemRecommendations` , `ItemRecommendations_Accounts_id`)
    REFERENCES `mydb`.`ItemRecommendations` (`idItemRecommendations` , `Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans_has_DVDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans_has_DVDs` (
  `id` INT NOT NULL,
  `Loans_idLoans` INT NOT NULL,
  `Loans_Accounts_id` INT NOT NULL,
  `DVDs_title` VARCHAR(45) NOT NULL,
  `DVDs_releaseDate` DATE NOT NULL,
  `DVDs_ItemRecommendations_idItemRecommendations` INT NOT NULL,
  `DVDs_ItemRecommendations_Accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Loans_idLoans`, `Loans_Accounts_id`, `DVDs_title`, `DVDs_releaseDate`, `DVDs_ItemRecommendations_idItemRecommendations`, `DVDs_ItemRecommendations_Accounts_id`),
  INDEX `fk_Loans_has_DVDs_DVDs1_idx` (`DVDs_title` ASC, `DVDs_releaseDate` ASC, `DVDs_ItemRecommendations_idItemRecommendations` ASC, `DVDs_ItemRecommendations_Accounts_id` ASC) VISIBLE,
  INDEX `fk_Loans_has_DVDs_Loans1_idx` (`Loans_idLoans` ASC, `Loans_Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_has_DVDs_Loans1`
    FOREIGN KEY (`Loans_idLoans` , `Loans_Accounts_id`)
    REFERENCES `mydb`.`Loans` (`idLoans` , `Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loans_has_DVDs_DVDs1`
    FOREIGN KEY (`DVDs_title` , `DVDs_releaseDate`)
    REFERENCES `mydb`.`DVDs` (`title` , `releaseDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans_has_Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans_has_Books` (
  `id` INT NOT NULL,
  `Loans_idLoans` INT NOT NULL,
  `Loans_Accounts_id` INT NOT NULL,
  `Books_isbn` VARCHAR(45) NOT NULL,
  `Books_ItemRecommendations_idItemRecommendations` INT NOT NULL,
  `Books_ItemRecommendations_Accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Loans_idLoans`, `Loans_Accounts_id`, `Books_isbn`, `Books_ItemRecommendations_idItemRecommendations`, `Books_ItemRecommendations_Accounts_id`),
  INDEX `fk_Loans_has_Books_Books1_idx` (`Books_isbn` ASC, `Books_ItemRecommendations_idItemRecommendations` ASC, `Books_ItemRecommendations_Accounts_id` ASC) VISIBLE,
  INDEX `fk_Loans_has_Books_Loans1_idx` (`Loans_idLoans` ASC, `Loans_Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_has_Books_Loans1`
    FOREIGN KEY (`Loans_idLoans` , `Loans_Accounts_id`)
    REFERENCES `mydb`.`Loans` (`idLoans` , `Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loans_has_Books_Books1`
    FOREIGN KEY (`Books_isbn`)
    REFERENCES `mydb`.`Books` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans_has_CDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans_has_CDs` (
  `id` INT NOT NULL,
  `Loans_idLoans` INT NOT NULL,
  `Loans_Accounts_id` INT NOT NULL,
  `CDs_title` VARCHAR(45) NOT NULL,
  `CDs_artist` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Loans_idLoans`, `Loans_Accounts_id`, `CDs_title`, `CDs_artist`),
  INDEX `fk_Loans_has_CDs_Loans1_idx` (`Loans_idLoans` ASC, `Loans_Accounts_id` ASC) VISIBLE,
  INDEX `fk_Loans_has_CDs_CDs1_idx` (`CDs_title` ASC, `CDs_artist` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_has_CDs_Loans1`
    FOREIGN KEY (`Loans_idLoans` , `Loans_Accounts_id`)
    REFERENCES `mydb`.`Loans` (`idLoans` , `Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loans_has_CDs_CDs1`
    FOREIGN KEY (`CDs_title` , `CDs_artist`)
    REFERENCES `mydb`.`CDs` (`title` , `artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
