-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 07:20:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `accountNumber` INT NOT NULL AUTO_INCREMENT,
  `dateCreated` DATE NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`accountNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `accountNumber` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Accounts1_idx` (`accountNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Accounts1`
    FOREIGN KEY (`accountNumber`)
    REFERENCES `mydb`.`Accounts` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemRecommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemRecommendations` (
  `idItemRecommendations` INT NOT NULL,
  `accountNumber` INT NOT NULL,
  `recommendedBooks` VARCHAR(45) NULL,
  `recommendedCDs` VARCHAR(45) NULL,
  `recommendedDVDs` VARCHAR(45) NULL,
  PRIMARY KEY (`idItemRecommendations`),
  INDEX `fk_ItemRecommendations_Accounts1_idx` (`accountNumber` ASC) VISIBLE,
  CONSTRAINT `fk_ItemRecommendations_Accounts1`
    FOREIGN KEY (`accountNumber`)
    REFERENCES `mydb`.`Accounts` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DVDs` (
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `ItemRecommendations_idItemRecommendations` INT NOT NULL,
  `releaseDate` DATE NULL,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`title`, `author`, `ItemRecommendations_idItemRecommendations`),
  INDEX `fk_DVDs_ItemRecommendations1_idx` (`ItemRecommendations_idItemRecommendations` ASC) VISIBLE,
  CONSTRAINT `fk_DVDs_ItemRecommendations1`
    FOREIGN KEY (`ItemRecommendations_idItemRecommendations`)
    REFERENCES `mydb`.`ItemRecommendations` (`idItemRecommendations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `isbn` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `publishingYear` YEAR(4) NULL,
  `author` VARCHAR(45) NULL,
  `ItemRecommendations_idItemRecommendations` INT NOT NULL,
  PRIMARY KEY (`isbn`, `ItemRecommendations_idItemRecommendations`),
  INDEX `fk_Books_ItemRecommendations1_idx` (`ItemRecommendations_idItemRecommendations` ASC) VISIBLE,
  CONSTRAINT `fk_Books_ItemRecommendations1`
    FOREIGN KEY (`ItemRecommendations_idItemRecommendations`)
    REFERENCES `mydb`.`ItemRecommendations` (`idItemRecommendations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CDs` (
  `title` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NULL,
  `recordLabel` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `ItemRecommendations_idItemRecommendations` INT NOT NULL,
  PRIMARY KEY (`title`, `artist`, `ItemRecommendations_idItemRecommendations`),
  INDEX `fk_CDs_ItemRecommendations1_idx` (`ItemRecommendations_idItemRecommendations` ASC) VISIBLE,
  CONSTRAINT `fk_CDs_ItemRecommendations1`
    FOREIGN KEY (`ItemRecommendations_idItemRecommendations`)
    REFERENCES `mydb`.`ItemRecommendations` (`idItemRecommendations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `idReservations` INT NOT NULL,
  `Accounts_id` INT NOT NULL,
  `DVDs_title` VARCHAR(45) NOT NULL,
  `DVDs_author` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `CDs_title` VARCHAR(45) NOT NULL,
  `CDs_artist` VARCHAR(45) NOT NULL,
  `DVD_res_num` INT NULL,
  `CD_res_num` INT NULL,
  `isbn_res_num` INT NULL,
  PRIMARY KEY (`idReservations`, `Accounts_id`, `DVDs_title`, `DVDs_author`, `isbn`, `CDs_title`, `CDs_artist`),
  INDEX `fk_Reservations_Accounts1_idx` (`Accounts_id` ASC) VISIBLE,
  INDEX `fk_Reservations_DVDs1_idx` (`DVDs_title` ASC, `DVDs_author` ASC) VISIBLE,
  INDEX `fk_Reservations_Books1_idx` (`isbn` ASC) VISIBLE,
  INDEX `fk_Reservations_CDs1_idx` (`CDs_title` ASC, `CDs_artist` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `mydb`.`Accounts` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_DVDs1`
    FOREIGN KEY (`DVDs_title` , `DVDs_author`)
    REFERENCES `mydb`.`DVDs` (`title` , `author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Books1`
    FOREIGN KEY (`isbn`)
    REFERENCES `mydb`.`Books` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_CDs1`
    FOREIGN KEY (`CDs_title` , `CDs_artist`)
    REFERENCES `mydb`.`CDs` (`title` , `artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `idLoans` INT NOT NULL,
  `Accounts_accountNumber` INT NOT NULL,
  PRIMARY KEY (`idLoans`),
  INDEX `fk_Loans_Accounts1_idx` (`Accounts_accountNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_Accounts1`
    FOREIGN KEY (`Accounts_accountNumber`)
    REFERENCES `mydb`.`Accounts` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVDLoans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DVDLoans` (
  `copyNumber` INT NOT NULL,
  `idLoans` INT NOT NULL,
  `DVDs_title` VARCHAR(45) NOT NULL,
  `DVDs_author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`copyNumber`, `idLoans`, `DVDs_title`, `DVDs_author`),
  INDEX `fk_Loans_has_DVDs_Loans1_idx` (`idLoans` ASC) VISIBLE,
  INDEX `fk_DVDLoans_DVDs1_idx` (`DVDs_title` ASC, `DVDs_author` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_has_DVDs_Loans1`
    FOREIGN KEY (`idLoans`)
    REFERENCES `mydb`.`Loans` (`idLoans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DVDLoans_DVDs1`
    FOREIGN KEY (`DVDs_title` , `DVDs_author`)
    REFERENCES `mydb`.`DVDs` (`title` , `author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookLoans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookLoans` (
  `copyNumber` INT NOT NULL,
  `idLoans` INT NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`copyNumber`, `idLoans`, `isbn`),
  INDEX `fk_Loans_has_Books_Books1_idx` (`isbn` ASC) VISIBLE,
  INDEX `fk_Loans_has_Books_Loans1_idx` (`idLoans` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_has_Books_Loans1`
    FOREIGN KEY (`idLoans`)
    REFERENCES `mydb`.`Loans` (`idLoans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loans_has_Books_Books1`
    FOREIGN KEY (`isbn`)
    REFERENCES `mydb`.`Books` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CDLoans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CDLoans` (
  `copyNumber` INT NOT NULL,
  `idLoans` INT NOT NULL,
  `CDs_title` VARCHAR(45) NOT NULL,
  `CDs_artist` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`copyNumber`, `idLoans`, `CDs_title`, `CDs_artist`),
  INDEX `fk_Loans_has_CDs_Loans1_idx` (`idLoans` ASC) VISIBLE,
  INDEX `fk_Loans_has_CDs_CDs1_idx` (`CDs_title` ASC, `CDs_artist` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_has_CDs_Loans1`
    FOREIGN KEY (`idLoans`)
    REFERENCES `mydb`.`Loans` (`idLoans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loans_has_CDs_CDs1`
    FOREIGN KEY (`CDs_title` , `CDs_artist`)
    REFERENCES `mydb`.`CDs` (`title` , `artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preferences` (
  `idPreferences` INT NOT NULL,
  `favoriteBooks` VARCHAR(45) NULL,
  `favoriteDVDs` VARCHAR(45) NULL,
  `favoriteCDs` VARCHAR(45) NULL,
  `booksCheckedOut` VARCHAR(45) NULL,
  `dvdsCheckedOut` VARCHAR(45) NULL,
  `cdsCheckedOut` VARCHAR(45) NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`idPreferences`),
  INDEX `fk_Preferences_Accounts1_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Preferences_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `mydb`.`Accounts` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
